### ISSUE TITLE
Websocket Issues

### ISSUE THREAD

**Issue by martygriffin** [mcardillo55/gdax-trader#16]
When running from the CLI, the script appears to be stuck a look opening/closing the websocket. Is this a known issue or is there something wrong with my setup?

-- CBPRO Websocket Closed ---
-- CBPRO Websocket Opened ---
-- CBPRO Websocket Closed ---
-- CBPRO Websocket Closed ---
-- CBPRO Websocket Opened ---
-- CBPRO Websocket Closed ---
-- CBPRO Websocket Closed ---

**Comment by martygriffin** [comment]
`2020-12-19 10:09:27.538637
Traceback (most recent call last):
  File "/Users/marty/GitHub/cbpro-trader/cbpro-trader/daemon/engine/TradeEngine.py", line 71, in update_orders
    self.recent_fills = sorted(self.temp_recent_fills, key=lambda x: x['created_at'], reverse=True)[:5]
  File "/Users/marty/GitHub/cbpro-trader/cbpro-trader/daemon/engine/TradeEngine.py", line 71, in <lambda>
    self.recent_fills = sorted(self.temp_recent_fills, key=lambda x: x['created_at'], reverse=True)[:5]
TypeError: string indices must be integers
2020-12-19 10:09:27.726466
Traceback (most recent call last):
  File "/Users/marty/GitHub/cbpro-trader/cbpro-trader/daemon/./cbpro-trader.py", line 110, in start
    product.order_book.process_message(msg)
AttributeError: 'OrderBookCustom' object has no attribute 'process_message'
2020-12-19 10:09:28.651176
Traceback (most recent call last):
  File "/Users/marty/GitHub/cbpro-trader/cbpro-trader/daemon/engine/TradeEngine.py", line 71, in update_orders
    self.recent_fills = sorted(self.temp_recent_fills, key=lambda x: x['created_at'], reverse=True)[:5]
  File "/Users/marty/GitHub/cbpro-trader/cbpro-trader/daemon/engine/TradeEngine.py", line 71, in <lambda>
    self.recent_fills = sorted(self.temp_recent_fills, key=lambda x: x['created_at'], reverse=True)[:5]
TypeError: string indices must be integers
2020-12-19 10:09:29.961216
Traceback (most recent call last):
  File "/Users/marty/GitHub/cbpro-trader/cbpro-trader/daemon/engine/TradeEngine.py", line 71, in update_orders
    self.recent_fills = sorted(self.temp_recent_fills, key=lambda x: x['created_at'], reverse=True)[:5]
  File "/Users/marty/GitHub/cbpro-trader/cbpro-trader/daemon/engine/TradeEngine.py", line 71, in <lambda>
    self.recent_fills = sorted(self.temp_recent_fills, key=lambda x: x['created_at'], reverse=True)[:5]
TypeError: string indices must be integers
`

**Comment by martygriffin** [comment]
Here it the content in error.log

2020-12-19 10:09:27.538637
Traceback (most recent call last):
  File "/Users/marty/GitHub/cbpro-trader/cbpro-trader/daemon/engine/TradeEngine.py", line 71, in update_orders
    self.recent_fills = sorted(self.temp_recent_fills, key=lambda x: x['created_at'], reverse=True)[:5]
  File "/Users/marty/GitHub/cbpro-trader/cbpro-trader/daemon/engine/TradeEngine.py", line 71, in <lambda>
    self.recent_fills = sorted(self.temp_recent_fills, key=lambda x: x['created_at'], reverse=True)[:5]
TypeError: string indices must be integers
2020-12-19 10:09:27.726466
Traceback (most recent call last):
  File "/Users/marty/GitHub/cbpro-trader/cbpro-trader/daemon/./cbpro-trader.py", line 110, in start
    product.order_book.process_message(msg)
AttributeError: 'OrderBookCustom' object has no attribute 'process_message'
2020-12-19 10:09:28.651176
Traceback (most recent call last):
  File "/Users/marty/GitHub/cbpro-trader/cbpro-trader/daemon/engine/TradeEngine.py", line 71, in update_orders
    self.recent_fills = sorted(self.temp_recent_fills, key=lambda x: x['created_at'], reverse=True)[:5]
  File "/Users/marty/GitHub/cbpro-trader/cbpro-trader/daemon/engine/TradeEngine.py", line 71, in <lambda>
    self.recent_fills = sorted(self.temp_recent_fills, key=lambda x: x['created_at'], reverse=True)[:5]
TypeError: string indices must be integers
2020-12-19 10:09:29.961216
Traceback (most recent call last):
  File "/Users/marty/GitHub/cbpro-trader/cbpro-trader/daemon/engine/TradeEngine.py", line 71, in update_orders
    self.recent_fills = sorted(self.temp_recent_fills, key=lambda x: x['created_at'], reverse=True)[:5]
  File "/Users/marty/GitHub/cbpro-trader/cbpro-trader/daemon/engine/TradeEngine.py", line 71, in <lambda>
    self.recent_fills = sorted(self.temp_recent_fills, key=lambda x: x['created_at'], reverse=True)[:5]
TypeError: string indices must be integers

**Comment by martygriffin** [comment]
2020-12-19 10:30:07.007735
Traceback (most recent call last):
  File "/Users/marty/GitHub/cbpro-trader/cbpro-trader/daemon/./cbpro-trader.py", line 110, in start
    product.order_book.process_message(msg)
AttributeError: 'OrderBookCustom' object has no attribute 'process_message'
2020-12-19 10:30:52.802056
Traceback (most recent call last):
  File "/Users/marty/GitHub/cbpro-trader/cbpro-trader/daemon/./cbpro-trader.py", line 110, in start
    product.order_book.process_message(msg)
AttributeError: 'OrderBookCustom' object has no attribute 'process_message'
2020-12-19 10:31:13.089105
Traceback (most recent call last):
  File "/Users/marty/GitHub/cbpro-trader/cbpro-trader/daemon/./cbpro-trader.py", line 110, in start
    product.order_book.process_message(msg)
AttributeError: 'OrderBookCustom' object has no attribute 'process_message'

**Comment by martygriffin** [comment]
I had a PR with what fixed both of these errors for me.
